//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#pragma warning disable 1591 //disables XML documentation warnings

namespace Sushi.Core
{
   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class PerformanceCounter
   {

      private string metricTypeField;

      private float countField;

            [XmlElement(Order = 0)]
      public string MetricType
      {
         get
         {
            return this.metricTypeField;
         }
         set
         {
            this.metricTypeField = value;
         }
      }

            [XmlElement(Order = 1)]
      public float Count
      {
         get
         {
            return this.countField;
         }
         set
         {
            this.countField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class DateRange
   {

      private DateTime beginField;

      private DateTime endField;

            [XmlElement(DataType = "date", Order = 0)]
      public DateTime Begin
      {
         get
         {
            return this.beginField;
         }
         set
         {
            this.beginField = value;
         }
      }

            [XmlElement(DataType = "date", Order = 1)]
      public DateTime End
      {
         get
         {
            return this.endField;
         }
         set
         {
            this.endField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Metric
   {

      private DateRange periodField;

      private string categoryField;

      private PerformanceCounter[] instanceField;

      private int pubYrField;

      private bool pubYrFieldSpecified;

            [XmlElement(Order = 0)]
      public DateRange Period
      {
         get
         {
            return this.periodField;
         }
         set
         {
            this.periodField = value;
         }
      }

            [XmlElement(Order = 1)]
      public string Category
      {
         get
         {
            return this.categoryField;
         }
         set
         {
            this.categoryField = value;
         }
      }

            [XmlElement("Instance", Order = 2)]
      public PerformanceCounter[] Instance
      {
         get
         {
            return this.instanceField;
         }
         set
         {
            this.instanceField = value;
         }
      }

            [XmlAttribute()]
      public int PubYr
      {
         get
         {
            return this.pubYrField;
         }
         set
         {
            this.pubYrField = value;
         }
      }

            [XmlIgnore()]
      public bool PubYrSpecified
      {
         get
         {
            return this.pubYrFieldSpecified;
         }
         set
         {
            this.pubYrFieldSpecified = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class ReportItem
   {

      private Identifier[] itemIdentifierField;

      private string itemPlatformField;

      private string itemPublisherField;

      private string itemNameField;

      private string itemDataTypeField;

      private Metric[] itemPerformanceField;

            [XmlElement("ItemIdentifier", Order = 0)]
      public Identifier[] ItemIdentifier
      {
         get
         {
            return this.itemIdentifierField;
         }
         set
         {
            this.itemIdentifierField = value;
         }
      }

            [XmlElement(Order = 1)]
      public string ItemPlatform
      {
         get
         {
            return this.itemPlatformField;
         }
         set
         {
            this.itemPlatformField = value;
         }
      }

            [XmlElement(Order = 2)]
      public string ItemPublisher
      {
         get
         {
            return this.itemPublisherField;
         }
         set
         {
            this.itemPublisherField = value;
         }
      }

            [XmlElement(Order = 3)]
      public string ItemName
      {
         get
         {
            return this.itemNameField;
         }
         set
         {
            this.itemNameField = value;
         }
      }

            [XmlElement(Order = 4)]
      public string ItemDataType
      {
         get
         {
            return this.itemDataTypeField;
         }
         set
         {
            this.itemDataTypeField = value;
         }
      }

            [XmlElement("ItemPerformance", Order = 5)]
      public Metric[] ItemPerformance
      {
         get
         {
            return this.itemPerformanceField;
         }
         set
         {
            this.itemPerformanceField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Identifier
   {

      private string typeField;

      private string valueField;

            [XmlElement(Order = 0)]
      public string Type
      {
         get
         {
            return this.typeField;
         }
         set
         {
            this.typeField = value;
         }
      }

            [XmlElement(Order = 1)]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Consortium
   {

      private string codeField;

      private string wellKnownNameField;

            [XmlElement(Order = 0)]
      public string Code
      {
         get
         {
            return this.codeField;
         }
         set
         {
            this.codeField = value;
         }
      }

            [XmlElement(Order = 1)]
      public string WellKnownName
      {
         get
         {
            return this.wellKnownNameField;
         }
         set
         {
            this.wellKnownNameField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Contact
   {

      private string contact1Field;

      private string emailField;

            [XmlElement("Contact", Order = 0)]
      public string Contact1
      {
         get
         {
            return this.contact1Field;
         }
         set
         {
            this.contact1Field = value;
         }
      }

            [XmlElement("E-mail", Order = 1)]
      public string Email
      {
         get
         {
            return this.emailField;
         }
         set
         {
            this.emailField = value;
         }
      }
   }

      [XmlInclude(typeof(Vendor))]
   [XmlInclude(typeof(Customer))]

   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Organization
   {

      private string nameField;

      private string idField;

      private Contact[] contactField;

      private string webSiteUrlField;

      private string logoUrlField;

            [XmlElement(Order = 0)]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }

            [XmlElement(Order = 1)]
      public string ID
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

            [XmlElement("Contact", Order = 2)]
      public Contact[] Contact
      {
         get
         {
            return this.contactField;
         }
         set
         {
            this.contactField = value;
         }
      }

            [XmlElement(DataType = "anyURI", Order = 3)]
      public string WebSiteUrl
      {
         get
         {
            return this.webSiteUrlField;
         }
         set
         {
            this.webSiteUrlField = value;
         }
      }

            [XmlElement(DataType = "anyURI", Order = 4)]
      public string LogoUrl
      {
         get
         {
            return this.logoUrlField;
         }
         set
         {
            this.logoUrlField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Vendor : Organization
   {
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Customer : Organization
   {

      private Consortium consortiumField;

      private Identifier[] institutionalIdentifierField;

            [XmlElement(Order = 0)]
      public Consortium Consortium
      {
         get
         {
            return this.consortiumField;
         }
         set
         {
            this.consortiumField = value;
         }
      }

            [XmlElement("InstitutionalIdentifier", Order = 1)]
      public Identifier[] InstitutionalIdentifier
      {
         get
         {
            return this.institutionalIdentifierField;
         }
         set
         {
            this.institutionalIdentifierField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/counter")]
   public partial class Report
   {

      private Vendor vendorField;

      private ReportCustomer[] customerField;

      private DateTime createdField;

      private bool createdFieldSpecified;

      private string idField;

      private string versionField;

      private string nameField;

      private string titleField;

            [XmlElement(Order = 0)]
      public Vendor Vendor
      {
         get
         {
            return this.vendorField;
         }
         set
         {
            this.vendorField = value;
         }
      }

            [XmlElement("Customer", Order = 1)]
      public ReportCustomer[] Customer
      {
         get
         {
            return this.customerField;
         }
         set
         {
            this.customerField = value;
         }
      }

            [XmlAttribute()]
      public DateTime Created
      {
         get
         {
            return this.createdField;
         }
         set
         {
            this.createdField = value;
         }
      }

            [XmlIgnore()]
      public bool CreatedSpecified
      {
         get
         {
            return this.createdFieldSpecified;
         }
         set
         {
            this.createdFieldSpecified = value;
         }
      }

            [XmlAttribute()]
      public string ID
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

            [XmlAttribute()]
      public string Version
      {
         get
         {
            return this.versionField;
         }
         set
         {
            this.versionField = value;
         }
      }

            [XmlAttribute()]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }

            [XmlAttribute()]
      public string Title
      {
         get
         {
            return this.titleField;
         }
         set
         {
            this.titleField = value;
         }
      }
   }

      public class Reports : List<Report> { };

   
   [Serializable()]
   [XmlType(AnonymousType = true, Namespace = "http://www.niso.org/schemas/counter")]
   public partial class ReportCustomer : Customer
   {

      private ReportItem[] reportItemsField;

            [XmlElement("ReportItems", Order = 0)]
      public ReportItem[] ReportItems
      {
         get
         {
            return this.reportItemsField;
         }
         set
         {
            this.reportItemsField = value;
         }
      }
   }

   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi/counter")]
   public partial class CounterReportResponse : ReportResponse
   {

      private Report[] reportField;

            [XmlArray(IsNullable = true, Order = 0)]
      [XmlArrayItem(Namespace = "http://www.niso.org/schemas/counter", IsNullable = false)]
      public Report[] Report
      {
         get
         {
            return this.reportField;
         }
         set
         {
            this.reportField = value;
         }
      }
   }

}