//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

using System;
using System.ServiceModel;
using System.Xml.Serialization;

#pragma warning disable 1591 //disables XML documentation warnings

namespace Sushi.Core
{
      [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportRequest
   {
    public ReportRequest(){}
      private Requestor requestorField;

      private CustomerReference customerReferenceField;

      private ReportDefinition reportDefinitionField;

      private DateTime createdField;

      private bool createdFieldSpecified;

      private string idField;

            [XmlElement(Order = 0)]
      public Requestor Requestor
      {
         get
         {
            return this.requestorField;
         }
         set
         {
            this.requestorField = value;
         }
      }

            [XmlElement(Order = 1)]
      public CustomerReference CustomerReference
      {
         get
         {
            return this.customerReferenceField;
         }
         set
         {
            this.customerReferenceField = value;
         }
      }

            [XmlElement(Order = 2)]
      public ReportDefinition ReportDefinition
      {
         get
         {
            return this.reportDefinitionField;
         }
         set
         {
            this.reportDefinitionField = value;
         }
      }

            [XmlAttribute()]
      public DateTime Created
      {
         get
         {
            return this.createdField;
         }
         set
         {
            this.createdField = value;
         }
      }

            [XmlIgnore()]
      public bool CreatedSpecified
      {
         get
         {
            return this.createdFieldSpecified;
         }
         set
         {
            this.createdFieldSpecified = value;
         }
      }

            [XmlAttribute()]
      public string ID
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Requestor
   {
    public Requestor(){}
      private string idField;

      private string nameField;

      private string emailField;

            [XmlElement(Order = 0)]
      public string ID
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

            [XmlElement(Order = 1)]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }

            [XmlElement(Order = 2)]
      public string Email
      {
         get
         {
            return this.emailField;
         }
         set
         {
            this.emailField = value;
         }
      }
   }

   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Activity
   {
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Exception
   {

      private int numberField;

      private ExceptionSeverity severityField;

      private string messageField;

      private string helpUrlField;

      private object dataField;

      private DateTime createdField;

      private bool createdFieldSpecified;

            [XmlElement(Order = 0)]
      public int Number
      {
         get
         {
            return this.numberField;
         }
         set
         {
            this.numberField = value;
         }
      }

            [XmlElement(Order = 1)]
      public ExceptionSeverity Severity
      {
         get
         {
            return this.severityField;
         }
         set
         {
            this.severityField = value;
         }
      }

            [XmlElement(Order = 2)]
      public string Message
      {
         get
         {
            return this.messageField;
         }
         set
         {
            this.messageField = value;
         }
      }

            [XmlElement(DataType = "anyURI", IsNullable = true, Order = 3)]
      public string HelpUrl
      {
         get
         {
            return this.helpUrlField;
         }
         set
         {
            this.helpUrlField = value;
         }
      }

            [XmlElement(IsNullable = true, Order = 4)]
      public object Data
      {
         get
         {
            return this.dataField;
         }
         set
         {
            this.dataField = value;
         }
      }

            [XmlAttribute()]
      public DateTime Created
      {
         get
         {
            return this.createdField;
         }
         set
         {
            this.createdField = value;
         }
      }

            [XmlIgnore()]
      public bool CreatedSpecified
      {
         get
         {
            return this.createdFieldSpecified;
         }
         set
         {
            this.createdFieldSpecified = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public enum ExceptionSeverity
   {

            Info,

            Debug,

            Warning,

            Error,

            Fatal,
   }

      //[System.Xml.Serialization.XmlIncludeAttribute(typeof(CounterReportResponse))]
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportResponse
   {

      private Exception[] exceptionField;

      private Requestor requestorField;

      private CustomerReference customerReferenceField;

      private ReportDefinition reportDefinitionField;

      private DateTime createdField;

      private bool createdFieldSpecified;

      private string idField;

            [XmlElement("Exception", IsNullable = true, Order = 0)]
      public Exception[] Exception
      {
         get
         {
            return this.exceptionField;
         }
         set
         {
            this.exceptionField = value;
         }
      }

            [XmlElement(Order = 1)]
      public Requestor Requestor
      {
         get
         {
            return this.requestorField;
         }
         set
         {
            this.requestorField = value;
         }
      }

            [XmlElement(Order = 2)]
      public CustomerReference CustomerReference
      {
         get
         {
            return this.customerReferenceField;
         }
         set
         {
            this.customerReferenceField = value;
         }
      }

            [XmlElement(Order = 3)]
      public ReportDefinition ReportDefinition
      {
         get
         {
            return this.reportDefinitionField;
         }
         set
         {
            this.reportDefinitionField = value;
         }
      }

            [XmlAttribute()]
      public DateTime Created
      {
         get
         {
            return this.createdField;
         }
         set
         {
            this.createdField = value;
         }
      }

            [XmlIgnore()]
      public bool CreatedSpecified
      {
         get
         {
            return this.createdFieldSpecified;
         }
         set
         {
            this.createdFieldSpecified = value;
         }
      }

            [XmlAttribute()]
      public string ID
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class CustomerReference
   {
    public CustomerReference(){}
      private string idField;

      private string nameField;

            [XmlElement(Order = 0)]
      public string ID
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

            [XmlElement(IsNullable = true, Order = 1)]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportDefinition
   {
    public ReportDefinition(){}
      private ReportDefinitionFilters filtersField;

      private string nameField;

      private string releaseField;

            [XmlElement(Order = 0)]
      public ReportDefinitionFilters Filters
      {
         get
         {
            return this.filtersField;
         }
         set
         {
            this.filtersField = value;
         }
      }

            [XmlAttribute()]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }

            [XmlAttribute()]
      public string Release
      {
         get
         {
            return this.releaseField;
         }
         set
         {
            this.releaseField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(AnonymousType = true, Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportDefinitionFilters
   {

      private Range usageDateRangeField;

            [XmlElement(Order = 0)]
      public Range UsageDateRange
      {
         get
         {
            return this.usageDateRangeField;
         }
         set
         {
            this.usageDateRangeField = value;
         }
      }
   }

   
   [Serializable()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Range
   {

      private DateTime beginField;

      private DateTime endField;

            [XmlElement(DataType = "date", Order = 0)]
      public DateTime Begin
      {
         get
         {
            return this.beginField;
         }
         set
         {
            this.beginField = value;
         }
      }

            [XmlElement(DataType = "date", Order = 1)]
      public DateTime End
      {
         get
         {
            return this.endField;
         }
         set
         {
            this.endField = value;
         }
      }
   }

   [MessageContract(IsWrapped = false)]
   public partial class GetReportRequest
   {

      [MessageBodyMember(Namespace = "http://www.niso.org/schemas/sushi/counter", Order = 0)]
      public ReportRequest ReportRequest;

      public GetReportRequest()
      {
      }

      public GetReportRequest(ReportRequest ReportRequest)
      {
         this.ReportRequest = ReportRequest;
      }
   }

   [MessageContract(IsWrapped = false)]
   public partial class GetReportResponse
   {

      [MessageBodyMember(Namespace = "http://www.niso.org/schemas/sushi/counter", Order = 0)]
      public CounterReportResponse ReportResponse;

      public GetReportResponse()
      {
      }

      public GetReportResponse(CounterReportResponse ReportResponse)
      {
         this.ReportResponse = ReportResponse;
      }
   }
}