//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DescriptorRecordSet {
    
    private DescriptorRecord[] descriptorRecordField;
    
    private DescriptorRecordSetLanguageCode languageCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DescriptorRecord")]
    public DescriptorRecord[] DescriptorRecord {
        get {
            return this.descriptorRecordField;
        }
        set {
            this.descriptorRecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DescriptorRecordSetLanguageCode LanguageCode {
        get {
            return this.languageCodeField;
        }
        set {
            this.languageCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DescriptorRecord : DescriptorReference {
    
    private normaldate dateCreatedField;
    
    private normaldate dateRevisedField;
    
    private normaldate dateEstablishedField;
    
    private string[] activeMeSHYearListField;
    
    private AllowableQualifier[] allowableQualifiersListField;
    
    private string annotationField;
    
    private string historyNoteField;
    
    private string onlineNoteField;
    
    private string publicMeSHNoteField;
    
    private string[] previousIndexingListField;
    
    private EntryCombination[] entryCombinationListField;
    
    private DescriptorReferredTo[] seeRelatedListField;
    
    private string considerAlsoField;
    
    private DescriptorReferredTo[] pharmacologicalActionListField;
    
    private string runningHeadField;
    
    private string[] treeNumberListField;
    
    private RecordOriginatorsList recordOriginatorsListField;
    
    private Concept[] conceptListField;
    
    private DescriptorRecordDescriptorClass descriptorClassField;
    
    public DescriptorRecord() {
        this.descriptorClassField = DescriptorRecordDescriptorClass.Item1;
    }
    
    /// <remarks/>
    public normaldate DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    public normaldate DateRevised {
        get {
            return this.dateRevisedField;
        }
        set {
            this.dateRevisedField = value;
        }
    }
    
    /// <remarks/>
    public normaldate DateEstablished {
        get {
            return this.dateEstablishedField;
        }
        set {
            this.dateEstablishedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Year", IsNullable=false)]
    public string[] ActiveMeSHYearList {
        get {
            return this.activeMeSHYearListField;
        }
        set {
            this.activeMeSHYearListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AllowableQualifier", IsNullable=false)]
    public AllowableQualifier[] AllowableQualifiersList {
        get {
            return this.allowableQualifiersListField;
        }
        set {
            this.allowableQualifiersListField = value;
        }
    }
    
    /// <remarks/>
    public string Annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    public string HistoryNote {
        get {
            return this.historyNoteField;
        }
        set {
            this.historyNoteField = value;
        }
    }
    
    /// <remarks/>
    public string OnlineNote {
        get {
            return this.onlineNoteField;
        }
        set {
            this.onlineNoteField = value;
        }
    }
    
    /// <remarks/>
    public string PublicMeSHNote {
        get {
            return this.publicMeSHNoteField;
        }
        set {
            this.publicMeSHNoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PreviousIndexing", IsNullable=false)]
    public string[] PreviousIndexingList {
        get {
            return this.previousIndexingListField;
        }
        set {
            this.previousIndexingListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("EntryCombination", IsNullable=false)]
    public EntryCombination[] EntryCombinationList {
        get {
            return this.entryCombinationListField;
        }
        set {
            this.entryCombinationListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SeeRelatedDescriptor", IsNullable=false)]
    public DescriptorReferredTo[] SeeRelatedList {
        get {
            return this.seeRelatedListField;
        }
        set {
            this.seeRelatedListField = value;
        }
    }
    
    /// <remarks/>
    public string ConsiderAlso {
        get {
            return this.considerAlsoField;
        }
        set {
            this.considerAlsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PharmacologicalAction", IsNullable=false)]
    public DescriptorReferredTo[] PharmacologicalActionList {
        get {
            return this.pharmacologicalActionListField;
        }
        set {
            this.pharmacologicalActionListField = value;
        }
    }
    
    /// <remarks/>
    public string RunningHead {
        get {
            return this.runningHeadField;
        }
        set {
            this.runningHeadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TreeNumber", IsNullable=false)]
    public string[] TreeNumberList {
        get {
            return this.treeNumberListField;
        }
        set {
            this.treeNumberListField = value;
        }
    }
    
    /// <remarks/>
    public RecordOriginatorsList RecordOriginatorsList {
        get {
            return this.recordOriginatorsListField;
        }
        set {
            this.recordOriginatorsListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Concept", IsNullable=false)]
    public Concept[] ConceptList {
        get {
            return this.conceptListField;
        }
        set {
            this.conceptListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DescriptorRecordDescriptorClass.Item1)]
    public DescriptorRecordDescriptorClass DescriptorClass {
        get {
            return this.descriptorClassField;
        }
        set {
            this.descriptorClassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="normal.date")]
[System.Xml.Serialization.XmlRootAttribute("DateCreated", Namespace="", IsNullable=false)]
public partial class normaldate {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <remarks/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public string Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    public string Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AllowableQualifier {
    
    private QualifierReference qualifierReferredToField;
    
    private string abbreviationField;
    
    /// <remarks/>
    public QualifierReference QualifierReferredTo {
        get {
            return this.qualifierReferredToField;
        }
        set {
            this.qualifierReferredToField = value;
        }
    }
    
    /// <remarks/>
    public string Abbreviation {
        get {
            return this.abbreviationField;
        }
        set {
            this.abbreviationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("QualifierReferredTo", Namespace="", IsNullable=false)]
public partial class QualifierReference {
    
    private string qualifierUIField;
    
    private QualifierName qualifierNameField;
    
    /// <remarks/>
    public string QualifierUI {
        get {
            return this.qualifierUIField;
        }
        set {
            this.qualifierUIField = value;
        }
    }
    
    /// <remarks/>
    public QualifierName QualifierName {
        get {
            return this.qualifierNameField;
        }
        set {
            this.qualifierNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class QualifierName {
    
    private string stringField;
    
    /// <remarks/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EntryCombination {
    
    private ECIN eCINField;
    
    private ECOUT eCOUTField;
    
    /// <remarks/>
    public ECIN ECIN {
        get {
            return this.eCINField;
        }
        set {
            this.eCINField = value;
        }
    }
    
    /// <remarks/>
    public ECOUT ECOUT {
        get {
            return this.eCOUTField;
        }
        set {
            this.eCOUTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ECIN : DescriptorReferredTo {
    
    private QualifierReference qualifierReferredToField;
    
    /// <remarks/>
    public QualifierReference QualifierReferredTo {
        get {
            return this.qualifierReferredToField;
        }
        set {
            this.qualifierReferredToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("SeeRelatedDescriptor", Namespace="", IsNullable=false)]
public partial class DescriptorReferredTo {
    
    private DescriptorReference descriptorReferredTo1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DescriptorReferredTo")]
    public DescriptorReference DescriptorReferredTo1 {
        get {
            return this.descriptorReferredTo1Field;
        }
        set {
            this.descriptorReferredTo1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DescriptorReferredTo", Namespace="", IsNullable=false)]
public partial class DescriptorReference {
    
    private string descriptorUIField;
    
    private DescriptorName descriptorNameField;
    
    /// <remarks/>
    public string DescriptorUI {
        get {
            return this.descriptorUIField;
        }
        set {
            this.descriptorUIField = value;
        }
    }
    
    /// <remarks/>
    public DescriptorName DescriptorName {
        get {
            return this.descriptorNameField;
        }
        set {
            this.descriptorNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DescriptorName {
    
    private string stringField;
    
    /// <remarks/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ECOUT : DescriptorReferredTo {
    
    private QualifierReference qualifierReferredToField;
    
    /// <remarks/>
    public QualifierReference QualifierReferredTo {
        get {
            return this.qualifierReferredToField;
        }
        set {
            this.qualifierReferredToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RecordOriginatorsList {
    
    private string recordOriginatorField;
    
    private string recordMaintainerField;
    
    private string recordAuthorizerField;
    
    /// <remarks/>
    public string RecordOriginator {
        get {
            return this.recordOriginatorField;
        }
        set {
            this.recordOriginatorField = value;
        }
    }
    
    /// <remarks/>
    public string RecordMaintainer {
        get {
            return this.recordMaintainerField;
        }
        set {
            this.recordMaintainerField = value;
        }
    }
    
    /// <remarks/>
    public string RecordAuthorizer {
        get {
            return this.recordAuthorizerField;
        }
        set {
            this.recordAuthorizerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Concept {
    
    private string conceptUIField;
    
    private ConceptName conceptNameField;
    
    private string conceptUMLSUIField;
    
    private string cASN1NameField;
    
    private string registryNumberField;
    
    private string scopeNoteField;
    
    private string translatorsEnglishScopeNoteField;
    
    private string translatorsScopeNoteField;
    
    private SemanticType[] semanticTypeListField;
    
    private string[] relatedRegistryNumberListField;
    
    private ConceptRelation[] conceptRelationListField;
    
    private Term[] termListField;
    
    private ConceptPreferredConceptYN preferredConceptYNField;
    
    /// <remarks/>
    public string ConceptUI {
        get {
            return this.conceptUIField;
        }
        set {
            this.conceptUIField = value;
        }
    }
    
    /// <remarks/>
    public ConceptName ConceptName {
        get {
            return this.conceptNameField;
        }
        set {
            this.conceptNameField = value;
        }
    }
    
    /// <remarks/>
    public string ConceptUMLSUI {
        get {
            return this.conceptUMLSUIField;
        }
        set {
            this.conceptUMLSUIField = value;
        }
    }
    
    /// <remarks/>
    public string CASN1Name {
        get {
            return this.cASN1NameField;
        }
        set {
            this.cASN1NameField = value;
        }
    }
    
    /// <remarks/>
    public string RegistryNumber {
        get {
            return this.registryNumberField;
        }
        set {
            this.registryNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ScopeNote {
        get {
            return this.scopeNoteField;
        }
        set {
            this.scopeNoteField = value;
        }
    }
    
    /// <remarks/>
    public string TranslatorsEnglishScopeNote {
        get {
            return this.translatorsEnglishScopeNoteField;
        }
        set {
            this.translatorsEnglishScopeNoteField = value;
        }
    }
    
    /// <remarks/>
    public string TranslatorsScopeNote {
        get {
            return this.translatorsScopeNoteField;
        }
        set {
            this.translatorsScopeNoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SemanticType", IsNullable=false)]
    public SemanticType[] SemanticTypeList {
        get {
            return this.semanticTypeListField;
        }
        set {
            this.semanticTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RelatedRegistryNumber", IsNullable=false)]
    public string[] RelatedRegistryNumberList {
        get {
            return this.relatedRegistryNumberListField;
        }
        set {
            this.relatedRegistryNumberListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ConceptRelation", IsNullable=false)]
    public ConceptRelation[] ConceptRelationList {
        get {
            return this.conceptRelationListField;
        }
        set {
            this.conceptRelationListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Term", IsNullable=false)]
    public Term[] TermList {
        get {
            return this.termListField;
        }
        set {
            this.termListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ConceptPreferredConceptYN PreferredConceptYN {
        get {
            return this.preferredConceptYNField;
        }
        set {
            this.preferredConceptYNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConceptName {
    
    private string stringField;
    
    /// <remarks/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SemanticType {
    
    private string semanticTypeUIField;
    
    private string semanticTypeNameField;
    
    /// <remarks/>
    public string SemanticTypeUI {
        get {
            return this.semanticTypeUIField;
        }
        set {
            this.semanticTypeUIField = value;
        }
    }
    
    /// <remarks/>
    public string SemanticTypeName {
        get {
            return this.semanticTypeNameField;
        }
        set {
            this.semanticTypeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConceptRelation {
    
    private string concept1UIField;
    
    private string concept2UIField;
    
    private string relationAttributeField;
    
    private ConceptRelationRelationName relationNameField;
    
    private bool relationNameFieldSpecified;
    
    /// <remarks/>
    public string Concept1UI {
        get {
            return this.concept1UIField;
        }
        set {
            this.concept1UIField = value;
        }
    }
    
    /// <remarks/>
    public string Concept2UI {
        get {
            return this.concept2UIField;
        }
        set {
            this.concept2UIField = value;
        }
    }
    
    /// <remarks/>
    public string RelationAttribute {
        get {
            return this.relationAttributeField;
        }
        set {
            this.relationAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ConceptRelationRelationName RelationName {
        get {
            return this.relationNameField;
        }
        set {
            this.relationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RelationNameSpecified {
        get {
            return this.relationNameFieldSpecified;
        }
        set {
            this.relationNameFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ConceptRelationRelationName {
    
    /// <remarks/>
    NRW,
    
    /// <remarks/>
    BRD,
    
    /// <remarks/>
    REL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Term {
    
    private string termUIField;
    
    private string stringField;
    
    private normaldate dateCreatedField;
    
    private string abbreviationField;
    
    private string sortVersionField;
    
    private string entryVersionField;
    
    private string[] thesaurusIDlistField;
    
    private string termNoteField;
    
    private TermConceptPreferredTermYN conceptPreferredTermYNField;
    
    private TermIsPermutedTermYN isPermutedTermYNField;
    
    private TermLexicalTag lexicalTagField;
    
    private TermPrintFlagYN printFlagYNField;
    
    private TermRecordPreferredTermYN recordPreferredTermYNField;
    
    /// <remarks/>
    public string TermUI {
        get {
            return this.termUIField;
        }
        set {
            this.termUIField = value;
        }
    }
    
    /// <remarks/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
    
    /// <remarks/>
    public normaldate DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    public string Abbreviation {
        get {
            return this.abbreviationField;
        }
        set {
            this.abbreviationField = value;
        }
    }
    
    /// <remarks/>
    public string SortVersion {
        get {
            return this.sortVersionField;
        }
        set {
            this.sortVersionField = value;
        }
    }
    
    /// <remarks/>
    public string EntryVersion {
        get {
            return this.entryVersionField;
        }
        set {
            this.entryVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ThesaurusID", IsNullable=false)]
    public string[] ThesaurusIDlist {
        get {
            return this.thesaurusIDlistField;
        }
        set {
            this.thesaurusIDlistField = value;
        }
    }
    
    /// <remarks/>
    public string TermNote {
        get {
            return this.termNoteField;
        }
        set {
            this.termNoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermConceptPreferredTermYN ConceptPreferredTermYN {
        get {
            return this.conceptPreferredTermYNField;
        }
        set {
            this.conceptPreferredTermYNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermIsPermutedTermYN IsPermutedTermYN {
        get {
            return this.isPermutedTermYNField;
        }
        set {
            this.isPermutedTermYNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermLexicalTag LexicalTag {
        get {
            return this.lexicalTagField;
        }
        set {
            this.lexicalTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermPrintFlagYN PrintFlagYN {
        get {
            return this.printFlagYNField;
        }
        set {
            this.printFlagYNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermRecordPreferredTermYN RecordPreferredTermYN {
        get {
            return this.recordPreferredTermYNField;
        }
        set {
            this.recordPreferredTermYNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum TermConceptPreferredTermYN {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum TermIsPermutedTermYN {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum TermLexicalTag {
    
    /// <remarks/>
    ABB,
    
    /// <remarks/>
    ABX,
    
    /// <remarks/>
    ACR,
    
    /// <remarks/>
    ACX,
    
    /// <remarks/>
    EPO,
    
    /// <remarks/>
    LAB,
    
    /// <remarks/>
    NAM,
    
    /// <remarks/>
    NON,
    
    /// <remarks/>
    TRD,
    
    /// <remarks/>
    Frelex,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum TermPrintFlagYN {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum TermRecordPreferredTermYN {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ConceptPreferredConceptYN {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DescriptorRecordDescriptorClass {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DescriptorRecordSetLanguageCode {
    
    /// <remarks/>
    cze,
    
    /// <remarks/>
    dut,
    
    /// <remarks/>
    eng,
    
    /// <remarks/>
    fin,
    
    /// <remarks/>
    fre,
    
    /// <remarks/>
    ger,
    
    /// <remarks/>
    ita,
    
    /// <remarks/>
    jpn,
    
    /// <remarks/>
    lav,
    
    /// <remarks/>
    por,
    
    /// <remarks/>
    scr,
    
    /// <remarks/>
    slv,
    
    /// <remarks/>
    spa,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ActiveMeSHYearList {
    
    private string[] yearField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Year")]
    public string[] Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AllowableQualifiersList {
    
    private AllowableQualifier[] allowableQualifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AllowableQualifier")]
    public AllowableQualifier[] AllowableQualifier {
        get {
            return this.allowableQualifierField;
        }
        set {
            this.allowableQualifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EntryCombinationList {
    
    private EntryCombination[] entryCombinationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntryCombination")]
    public EntryCombination[] EntryCombination {
        get {
            return this.entryCombinationField;
        }
        set {
            this.entryCombinationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PreviousIndexingList {
    
    private string[] previousIndexingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PreviousIndexing")]
    public string[] PreviousIndexing {
        get {
            return this.previousIndexingField;
        }
        set {
            this.previousIndexingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SeeRelatedList {
    
    private DescriptorReferredTo[] seeRelatedDescriptorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SeeRelatedDescriptor")]
    public DescriptorReferredTo[] SeeRelatedDescriptor {
        get {
            return this.seeRelatedDescriptorField;
        }
        set {
            this.seeRelatedDescriptorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TreeNumberList {
    
    private string[] treeNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TreeNumber")]
    public string[] TreeNumber {
        get {
            return this.treeNumberField;
        }
        set {
            this.treeNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConceptList {
    
    private Concept[] conceptField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Concept")]
    public Concept[] Concept {
        get {
            return this.conceptField;
        }
        set {
            this.conceptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConceptRelationList {
    
    private ConceptRelation[] conceptRelationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ConceptRelation")]
    public ConceptRelation[] ConceptRelation {
        get {
            return this.conceptRelationField;
        }
        set {
            this.conceptRelationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PharmacologicalActionList {
    
    private DescriptorReferredTo[] pharmacologicalActionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PharmacologicalAction")]
    public DescriptorReferredTo[] PharmacologicalAction {
        get {
            return this.pharmacologicalActionField;
        }
        set {
            this.pharmacologicalActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RelatedRegistryNumberList {
    
    private string[] relatedRegistryNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelatedRegistryNumber")]
    public string[] RelatedRegistryNumber {
        get {
            return this.relatedRegistryNumberField;
        }
        set {
            this.relatedRegistryNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SemanticTypeList {
    
    private SemanticType[] semanticTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SemanticType")]
    public SemanticType[] SemanticType {
        get {
            return this.semanticTypeField;
        }
        set {
            this.semanticTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TermList {
    
    private Term[] termField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Term")]
    public Term[] Term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ThesaurusIDlist {
    
    private string[] thesaurusIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ThesaurusID")]
    public string[] ThesaurusID {
        get {
            return this.thesaurusIDField;
        }
        set {
            this.thesaurusIDField = value;
        }
    }
}
