//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2V2.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R2V2.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry this account already exists..
        /// </summary>
        public static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry this account does not exist in prelude..
        /// </summary>
        public static string AccountDoesNotExistInPrelude {
            get {
                return ResourceManager.GetString("AccountDoesNotExistInPrelude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Title is a Brandon Hill Selection.
        /// </summary>
        public static string BrandonHillSelection {
            get {
                return ResourceManager.GetString("BrandonHillSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password is incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Doody Core Title.
        /// </summary>
        public static string DoodyCoreTitle {
            get {
                return ResourceManager.GetString("DoodyCoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an Essential Doody Core Title.
        /// </summary>
        public static string EssentialDoodyCoreTitle {
            get {
                return ResourceManager.GetString("EssentialDoodyCoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Available.
        /// </summary>
        public static string FullTextAvailable {
            get {
                return ResourceManager.GetString("FullTextAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is available in your collection..
        /// </summary>
        public static string FullTextAvailableTooltip {
            get {
                return ResourceManager.GetString("FullTextAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Max Length is 20 and Minimum Length is 4 characters.
        /// </summary>
        public static string PasswordMinMaxLength {
            get {
                return ResourceManager.GetString("PasswordMinMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 to 20 characters and contain 3 out of 4: Upper case, Lower case, Number, Special Character `~!@#$%^&amp;*()&gt;&lt;?:,./\;&apos;|-.
        /// </summary>
        public static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is not currently accessible. If you want your library to consider purchasing it, click “Suggest for Purchase” and complete the title request form. Let your library know you are interested in using this title. The information for this title will be automatically included in your message..
        /// </summary>
        public static string PdaAccessDenied {
            get {
                return ResourceManager.GetString("PdaAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is being considered for purchase by the library and is currently not accessible. This title is on PDA and has triggered because it reached the maximum views. .
        /// </summary>
        public static string PdaAccessDeniedAdmin {
            get {
                return ResourceManager.GetString("PdaAccessDeniedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is being considered for purchase by the library and is currently not accessible. Please {0} to contact your library administrator for more information. The information for this title will be automatically included in your message..
        /// </summary>
        public static string PdaResourceAccessDenied {
            get {
                return ResourceManager.GetString("PdaResourceAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a password.
        /// </summary>
        public static string PleaseFillInPassword {
            get {
                return ResourceManager.GetString("PleaseFillInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new password is required to reactivate an account.
        /// </summary>
        public static string ReactivatePleaseFillInPassword {
            get {
                return ResourceManager.GetString("ReactivatePleaseFillInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have failed the Recaptcha entry form to many times. Please try again later..
        /// </summary>
        public static string RecaptchaDenied {
            get {
                return ResourceManager.GetString("RecaptchaDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource at this time. R2 users, please login or {0} for more information..
        /// </summary>
        public static string ResourceAccessDenied {
            get {
                return ResourceManager.GetString("ResourceAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content is currently unavailable because all of the licenses are in use. Please try again shortly..
        /// </summary>
        public static string ResourceAccessLocked {
            get {
                return ResourceManager.GetString("ResourceAccessLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title has been archived..
        /// </summary>
        public static string TitleArchived {
            get {
                return ResourceManager.GetString("TitleArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title has been officially declared out of print by the publisher and remains available for viewing with institutional ownership..
        /// </summary>
        public static string TitleArchivedTooltip {
            get {
                return ResourceManager.GetString("TitleArchivedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Contents Available.
        /// </summary>
        public static string TOCAvailable {
            get {
                return ResourceManager.GetString("TOCAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is being considered for purchase by the library and is currently not accessible. Please contact your library administrator for more information..
        /// </summary>
        public static string TOCAvailablePDATooltip {
            get {
                return ResourceManager.GetString("TOCAvailablePDATooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table of contents is available in your collection..
        /// </summary>
        public static string TOCAvailableTooltip {
            get {
                return ResourceManager.GetString("TOCAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UserIsRequired {
            get {
                return ResourceManager.GetString("UserIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Username already exists. Please try a different UserName..
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This UserName is already in use..
        /// </summary>
        public static string UserNameAlreadyInUse {
            get {
                return ResourceManager.GetString("UserNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain commas.
        /// </summary>
        public static string UserNameCommas {
            get {
                return ResourceManager.GetString("UserNameCommas", resourceCulture);
            }
        }
    }
}
