//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Xml;

namespace R2V2.WindowsService.PrecisionSearch {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(Namespace="http://www.medinfonow.com/PrecisionSearchWebServices", ConfigurationName="PrecisionSearch.PSWebServicesSoap")]
    public interface PSWebServicesSoap {
        
        [OperationContract(Action="/Executes all Functions after validating request", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        XmlNode execute(string AuthToken, string soapRequest);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface PSWebServicesSoapChannel : PSWebServicesSoap, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class PSWebServicesSoapClient : ClientBase<PSWebServicesSoap>, PSWebServicesSoap {
        
        public PSWebServicesSoapClient() {
        }
        
        public PSWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PSWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSWebServicesSoapClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSWebServicesSoapClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XmlNode execute(string AuthToken, string soapRequest) {
            return base.Channel.execute(AuthToken, soapRequest);
        }
    }
}
