//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


[GeneratedCode("xsd", "4.0.30319.1")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(Namespace="", IsNullable=false)]
public partial class PSWS_Request {
    
    private string methodNameField;
    
    private PSWS_RequestParameters parametersField;
    
        public string MethodName {
        get {
            return this.methodNameField;
        }
        set {
            this.methodNameField = value;
        }
    }
    
        public PSWS_RequestParameters Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
}

[GeneratedCode("xsd", "4.0.30319.1")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class PSWS_RequestParameters {
    
    private string sourceCodeField;
    
    private string accountIDField;
    
    private string customerNameField;
    
    private string customerAddress1Field;
    
    private string customerAddress2Field;
    
    private string customerCityField;
    
    private string customerStateField;
    
    private string customerPostalCodeField;
    
    private string customerCountryField;
    
    private string customerPhoneField;
    
    private string customerAdminContactLastNameField;
    
    private string customerAdminContactFirstNameField;
    
    private string customerAdminContactEmailAddressField;
    
    private string customerAdminContactAddress1Field;
    
    private string customerAdminContactAddress2Field;
    
    private string customerAdminContactCityField;
    
    private string customerAdminContactStateField;
    
    private string customerAdminContactPostalCodeField;
    
    private string customerAdminContactCountryField;
    
    private string customerAdminContactPhoneField;
    
    private string customerAdminContactJobTitleField;
    
    private string customerOrganizationTypeField;
    
    private string agreementTypeField;
    
    private string startDateField;
    
    private string endDateField;
    
        public string SourceCode {
        get {
            return this.sourceCodeField;
        }
        set {
            this.sourceCodeField = value;
        }
    }
    
        public string AccountID {
        get {
            return this.accountIDField;
        }
        set {
            this.accountIDField = value;
        }
    }
    
        public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
        public string CustomerAddress1 {
        get {
            return this.customerAddress1Field;
        }
        set {
            this.customerAddress1Field = value;
        }
    }
    
        public string CustomerAddress2 {
        get {
            return this.customerAddress2Field;
        }
        set {
            this.customerAddress2Field = value;
        }
    }
    
        public string CustomerCity {
        get {
            return this.customerCityField;
        }
        set {
            this.customerCityField = value;
        }
    }
    
        public string CustomerState {
        get {
            return this.customerStateField;
        }
        set {
            this.customerStateField = value;
        }
    }
    
        public string CustomerPostalCode {
        get {
            return this.customerPostalCodeField;
        }
        set {
            this.customerPostalCodeField = value;
        }
    }
    
        public string CustomerCountry {
        get {
            return this.customerCountryField;
        }
        set {
            this.customerCountryField = value;
        }
    }
    
        public string CustomerPhone {
        get {
            return this.customerPhoneField;
        }
        set {
            this.customerPhoneField = value;
        }
    }
    
        public string CustomerAdminContactLastName {
        get {
            return this.customerAdminContactLastNameField;
        }
        set {
            this.customerAdminContactLastNameField = value;
        }
    }
    
        public string CustomerAdminContactFirstName {
        get {
            return this.customerAdminContactFirstNameField;
        }
        set {
            this.customerAdminContactFirstNameField = value;
        }
    }
    
        public string CustomerAdminContactEmailAddress {
        get {
            return this.customerAdminContactEmailAddressField;
        }
        set {
            this.customerAdminContactEmailAddressField = value;
        }
    }
    
        public string CustomerAdminContactAddress1 {
        get {
            return this.customerAdminContactAddress1Field;
        }
        set {
            this.customerAdminContactAddress1Field = value;
        }
    }
    
        public string CustomerAdminContactAddress2 {
        get {
            return this.customerAdminContactAddress2Field;
        }
        set {
            this.customerAdminContactAddress2Field = value;
        }
    }
    
        public string CustomerAdminContactCity {
        get {
            return this.customerAdminContactCityField;
        }
        set {
            this.customerAdminContactCityField = value;
        }
    }
    
        public string CustomerAdminContactState {
        get {
            return this.customerAdminContactStateField;
        }
        set {
            this.customerAdminContactStateField = value;
        }
    }
    
        public string CustomerAdminContactPostalCode {
        get {
            return this.customerAdminContactPostalCodeField;
        }
        set {
            this.customerAdminContactPostalCodeField = value;
        }
    }
    
        public string CustomerAdminContactCountry {
        get {
            return this.customerAdminContactCountryField;
        }
        set {
            this.customerAdminContactCountryField = value;
        }
    }
    
        public string CustomerAdminContactPhone {
        get {
            return this.customerAdminContactPhoneField;
        }
        set {
            this.customerAdminContactPhoneField = value;
        }
    }
    
        public string CustomerAdminContactJobTitle {
        get {
            return this.customerAdminContactJobTitleField;
        }
        set {
            this.customerAdminContactJobTitleField = value;
        }
    }
    
        public string CustomerOrganizationType {
        get {
            return this.customerOrganizationTypeField;
        }
        set {
            this.customerOrganizationTypeField = value;
        }
    }
    
        public string AgreementType {
        get {
            return this.agreementTypeField;
        }
        set {
            this.agreementTypeField = value;
        }
    }
    
        public string StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
        public string EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
}
